spring:
  mail:
    host: smtp.googlemail.com
    port: 587
    username: noreply.connectverse@gmail.com
    password: yulsuctbziffnhge
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 695310808073-273d8bafanlk75o5pumtom9lp1oagedq.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: f64b3b2b131b3effc573
            client-secret: 0491edb487ed63cfd6b77fd15a0a44580ad31772
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      
auth:
  oauth-path: /login/oauth2/code/**
  refresh-token: '864000000'
  issuer: GMC
  auth-url: /auth/login
  expeiry: '8640000'
  jwt-secret: anywaynavins3dnevereverhelpsomeoneunlesstheyaskforit

settings:
  app:
    pageSize: 10
    disableSecurity: true
    batchFilesPath: ./batch-files/
    
management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - beans
        - threaddump
